taskName: pipelinesTask
primaryResource: vigneshs
gitProvider: myGithub
artifactory: myArtifactory # rename if the artifactory integration is different
repoPath: VigneshJfrog/jfrog-pipelines-task/
mainBranch: main
protocol: https
buildOnCommit: true
publishOnCommit: false
pipelineName: "jfrog-pipelines-task"
